//! Generates the runtime's universal-wallet schema artifacts.
//!
//! Output (written to `OUT_DIR/autogenerated.rs`):
//!
//! - `pub const CHAIN_HASH: [u8; 32]` — derived deterministically
//!   from the runtime's universal-wallet `Schema`.
//!   Used by the SDK's transaction authenticator to bind every
//!   signed tx to this exact runtime composition; clients on a
//!   different runtime composition produce signatures that won't
//!   verify.
//! - `pub const SCHEMA_BORSH: &[u8]` — the same schema serialised
//!   for guests / over-the-wire schema fetches.
//! - `pub const SCHEMA_JSON: &str` — human-readable form, served at
//!   `/schema` for wallet-config consumers.
//!
//! Mirrors the SDK demo's `examples/demo-rollup/stf/build.rs`. We
//! pin the generation to a `MockDaSpec + MockZkvm + MultiAddressEvm`
//! spec because the schema only depends on the runtime's per-module
//! types and address shape — not on the specific DA layer or ZkVM.
//! Anyone validating txs against this chain (rollup binary, client
//! library, future provers) sees the same `CHAIN_HASH` regardless
//! of which spec they instantiate.

use ligate_stf_declaration::Runtime;
use sov_address::MultiAddressEvm;
use sov_mock_da::MockDaSpec;
use sov_mock_zkvm::MockZkvm;
use sov_modules_api::configurable_spec::ConfigurableSpec;

#[cfg(feature = "native")]
type ExecMode = sov_modules_api::execution_mode::Native;

#[cfg(not(feature = "native"))]
type ExecMode = sov_modules_api::execution_mode::Zk;

type S = ConfigurableSpec<MockDaSpec, MockZkvm, MockZkvm, MultiAddressEvm, ExecMode>;

fn main() -> anyhow::Result<()> {
    // `sov_build`'s default `out_dir` is `.artifacts/` relative to
    // the build CWD — that style requires committing or
    // .gitignoring the directory in the source tree. Cargo's
    // `OUT_DIR` is the standard place for build-script output and
    // gets cleaned up between target dirs automatically, so we
    // point at it instead.
    let out_dir =
        std::env::var_os("OUT_DIR").expect("`OUT_DIR` must be set by cargo for build scripts");
    sov_build::Options::builder().out_dir(out_dir).build().apply::<S, Runtime<S>>()
}
