//! Fuzz the Bech32m decoders for the four typed identifiers
//! generated by `impl_hash32_type!`: `SchemaId` (lsc1), `AttestorSetId`
//! (las1), `PayloadHash` (lph1), `PubKey` (lpk1).
//!
//! These types are used in REST path parameters and JSON
//! serialization. A panic in `FromStr` for any of them would
//! propagate into the HTTP handler and crash the node on a
//! malformed query.
//!
//! Per #46 (Bech32 lig1 convention), every external identifier
//! goes through this decoder; this is one of the highest-volume
//! adversarial-input surfaces on the chain.

#![no_main]

use core::str::FromStr;

use attestation::{AttestorSetId, PayloadHash, PubKey, SchemaId};
use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    // Treat the input as a UTF-8 string; reject non-UTF-8 early.
    // Bech32 inputs are pure ASCII anyway, so this is a no-op for
    // any plausible attacker payload.
    let Ok(s) = core::str::from_utf8(data) else {
        return;
    };

    // Each FromStr must surface bad inputs as `Err`, never a panic.
    let _ = SchemaId::from_str(s);
    let _ = AttestorSetId::from_str(s);
    let _ = PayloadHash::from_str(s);
    let _ = PubKey::from_str(s);
});
