//! Ligate attestation protocol, generic on-chain attestation primitive.
//!
//! This crate implements the protocol's data shapes and state layout.
//! See [`docs/protocol/attestation-v0.md`][spec] for the full specification.
//!
//! [spec]: https://github.com/ligate-io/ligate-chain/blob/main/docs/protocol/attestation-v0.md
//!
//! # Protocol summary
//!
//! Three entities, three `StateMap`s, three call messages:
//!
//! | Entity | Identified by | Registered by |
//! |---|---|---|
//! | [`AttestorSet`]  | `SHA-256(members ‖ threshold)` | [`CallMessage::RegisterAttestorSet`] |
//! | [`Schema`]       | `SHA-256(owner ‖ name ‖ version)` | [`CallMessage::RegisterSchema`] |
//! | [`Attestation`]  | `(schema_id, payload_hash)` | [`CallMessage::SubmitAttestation`] |
//!
//! Reads (`get_schema`, `get_attestor_set`, `get_attestation`, listing variants)
//! are exposed via query RPC and deliberately absent from [`CallMessage`] ,
//! verification is a read, not a state-mutating transaction.
//!
//! # Scope of this crate
//!
//! Protocol-shaped data types + the [`AttestationModule`] struct with its
//! state layout wired to the real `sov_modules_api::StateMap`. State
//! transition implementations (`call`), genesis config, RPC endpoints,
//! and fee-split enforcement land in sibling issues (#7, #8, #20-#22).

#![deny(missing_docs)]

use borsh::{BorshDeserialize, BorshSerialize};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use sov_bank::{Amount, Bank, Coins, TokenId};
use sov_modules_api::prelude::UnwrapInfallible;
use sov_modules_api::{
    Context, DaSpec, EventEmitter, GenesisState, Module, ModuleId, ModuleInfo, Spec, StateMap,
    StateValue, TxState,
};
use thiserror::Error as ThisError;

// ----- Primitive aliases ------------------------------------------------------

/// 32-byte SHA-256 digest. Used internally for content-hash work and
/// as the inner representation of the typed id newtypes below.
///
/// Distinct from a chain account address (`S::Address`, 28 bytes in
/// the canonical SDK config). For protocol-level identifiers (schema
/// ids, attestor-set ids, attestation ids, payload hashes) we use the
/// typed Bech32-encoded newtypes generated by `impl_hash32_type!`.
/// Account fields like [`Schema::owner`] and [`Attestation::submitter`]
/// use `S::Address` directly.
pub type Hash32 = [u8; 32];

// Per #46, every Ligate-minted identifier has a typed Bech32 prefix.
// `impl_hash32_type!` generates a newtype around `[u8; N]` plus
// Display, FromStr, Borsh, Serde, JsonSchema, and bech32m encoding /
// decoding using the supplied prefix. The state layer requires keys
// to be `FromStr + Display`; these macro calls satisfy that.
//
// Each macro invocation generates helper functions
// (`__impl_hash32_type_prefix`, `__bech32_hrp`, `__bech32_conversion_impls`)
// scoped to its module. We put each call in its own private module
// to keep those names from colliding, then re-export the public
// types up to the crate root.

mod schema_id_mod {
    sov_modules_api::impl_hash32_type!(SchemaId, SchemaIdBech32, "lsc");
}
pub use schema_id_mod::{SchemaId, SchemaIdBech32};

mod attestor_set_id_mod {
    sov_modules_api::impl_hash32_type!(AttestorSetId, AttestorSetIdBech32, "las");
}
pub use attestor_set_id_mod::{AttestorSetId, AttestorSetIdBech32};

mod payload_hash_mod {
    sov_modules_api::impl_hash32_type!(PayloadHash, PayloadHashBech32, "lph");
}
pub use payload_hash_mod::{PayloadHash, PayloadHashBech32};

mod pubkey_mod {
    sov_modules_api::impl_hash32_type!(PubKey, PubKeyBech32, "lpk");
}
pub use pubkey_mod::{PubKey, PubKeyBech32};

/// Compound attestation receipt identifier: `(schema_id, payload_hash)`.
///
/// Hand-rolled (rather than macro-generated like the 32-byte id types)
/// because Serde's blanket array impls don't cover `[u8; 64]`. Storing
/// the two halves as separate fields sidesteps that without losing the
/// "single typed key" property the state-map layer needs.
///
/// Display/FromStr roundtrip uses a `<schema_id>:<payload_hash>`
/// colon-separated form, where each side is the bech32 encoding of
/// the underlying `SchemaId` / `PayloadHash`. Suitable for explorer
/// URLs and CLI surfaces; bech32 round-trips through it cleanly.
#[derive(
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
    Hash,
    BorshSerialize,
    BorshDeserialize,
    Serialize,
    Deserialize,
)]
pub struct AttestationId {
    /// Schema this attestation is bound to.
    pub schema_id: SchemaId,
    /// Caller-computed digest of the off-chain payload.
    pub payload_hash: PayloadHash,
}

impl AttestationId {
    /// Build an [`AttestationId`] from its `(schema_id, payload_hash)` pair.
    pub fn from_pair(schema_id: &SchemaId, payload_hash: &PayloadHash) -> Self {
        Self { schema_id: *schema_id, payload_hash: *payload_hash }
    }
}

impl core::fmt::Display for AttestationId {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}:{}", self.schema_id, self.payload_hash)
    }
}

impl core::str::FromStr for AttestationId {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let (sid, ph) = s
            .split_once(':')
            .ok_or_else(|| anyhow::anyhow!("expected `<schema_id>:<payload_hash>`"))?;
        Ok(Self {
            schema_id: SchemaId::from_str(sid)?,
            payload_hash: PayloadHash::from_str(ph)?,
        })
    }
}

impl schemars::JsonSchema for AttestationId {
    fn schema_name() -> String {
        "AttestationId".to_string()
    }

    fn json_schema(gen: &mut schemars::gen::SchemaGenerator) -> schemars::schema::Schema {
        // Surface as a string in the schema; we'll regex-validate the
        // colon-separated form when the REST API hits real users.
        <String as schemars::JsonSchema>::json_schema(gen)
    }
}

// ----- AttestorSet ------------------------------------------------------------

/// A quorum of signers. **Immutable once registered**, to "rotate" an
/// attestor set, register a new one and bump any affected schema to a new
/// version that points at the new [`AttestorSetId`].
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, BorshSerialize, BorshDeserialize)]
pub struct AttestorSet {
    /// Ordered list of attestor public keys.
    ///
    /// Order matters for the derivation of [`AttestorSetId`], callers
    /// must supply a canonical (e.g. lexicographic) ordering, and the
    /// state transition re-hashes to verify before accepting.
    pub members: Vec<PubKey>,
    /// M-of-N signatures required. `threshold ≤ members.len()` is an
    /// invariant the state transition enforces at registration time.
    pub threshold: u8,
}

/// Single attestor's co-signature on an [`Attestation`].
///
/// `sig` is `Vec<u8>` rather than a fixed-size array so we can support
/// different signature schemes (ed25519 = 64 bytes, BLS = 48, etc.) under
/// the same type; exact validation is scheme-specific and lives in the
/// state transition.
#[derive(
    Clone,
    Debug,
    PartialEq,
    Eq,
    Serialize,
    Deserialize,
    BorshSerialize,
    BorshDeserialize,
    schemars::JsonSchema,
)]
pub struct AttestorSignature {
    /// Signer's public key. Must appear in the schema's
    /// [`AttestorSet::members`] for the signature to be accepted.
    pub pubkey: PubKey,
    /// Signature over the canonical Borsh encoding of
    /// [`SignedAttestationPayload`].
    pub sig: Vec<u8>,
}

// ----- Schema -----------------------------------------------------------------

/// An app's attestation shape and rules.
///
/// Registration is permissionless, anyone with enough $LGT to pay the
/// registration fee can register a schema. Name collisions across owners
/// are allowed (different `owner` bytes → different [`SchemaId`]); social
/// identity of the "real" schema owner lives off-chain.
///
/// Generic over a chain `Spec` because the `owner` and `fee_routing_addr`
/// fields are real chain account addresses (currently 28 bytes per the
/// SDK's standard address shape) rather than 32-byte content hashes.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, BorshSerialize, BorshDeserialize)]
#[serde(bound = "S::Address: Serialize + serde::de::DeserializeOwned")]
pub struct Schema<S: Spec> {
    /// Registrant; receives control over schema version upgrades and
    /// [`Schema::fee_routing_addr`]. Schema fields are otherwise immutable.
    pub owner: S::Address,
    /// Human-readable handle, e.g. `"themisra.proof-of-prompt"`. Only
    /// unique within an `owner`'s namespace.
    pub name: String,
    /// Monotonic per-schema version. Bumping version = new
    /// [`SchemaId`] = new [`Schema`] entry; no in-place mutation.
    pub version: u32,
    /// [`AttestorSetId`] of the quorum that must sign attestations under
    /// this schema. Must reference a registered [`AttestorSet`].
    pub attestor_set: AttestorSetId,
    /// Share of the attestation fee routed to [`Schema::fee_routing_addr`],
    /// in basis points (1/10,000). Protocol caps this at 5000 (50%) in
    /// v0; governance-adjustable in v1+.
    pub fee_routing_bps: u16,
    /// Destination of the builder's fee share. `None` iff
    /// `fee_routing_bps == 0`, the state transition rejects dangling
    /// routing and orphan addresses at registration time.
    pub fee_routing_addr: Option<S::Address>,
}

impl<S: Spec> Schema<S> {
    /// Derive a [`SchemaId`] from its defining tuple.
    ///
    /// Formula: `SHA-256(owner_bytes ‖ name ‖ version_le_bytes)`, where
    /// `owner_bytes` is `S::Address::as_ref()`. The state-transition
    /// re-runs this at registration and stores the derived id on-chain,
    /// so downstream consumers never have to trust a submitter-claimed id.
    pub fn derive_id(owner: &S::Address, name: &str, version: u32) -> SchemaId {
        let mut hasher = Sha256::new();
        hasher.update(owner.as_ref());
        hasher.update(name.as_bytes());
        hasher.update(version.to_le_bytes());
        let bytes: [u8; 32] = hasher.finalize().into();
        SchemaId::from(bytes)
    }
}

impl AttestorSet {
    /// Derive an [`AttestorSetId`] from members + threshold.
    ///
    /// Members are **sorted internally** before hashing so the set id is
    /// independent of the caller's input order. The state transition
    /// stores members in the same sorted order it uses for derivation.
    /// Duplicate pubkeys are preserved (the state transition rejects
    /// sets with duplicates at registration).
    pub fn derive_id(members: &[PubKey], threshold: u8) -> AttestorSetId {
        let mut sorted = members.to_vec();
        // PubKey is the macro-generated newtype around [u8; 32]; the
        // macro doesn't derive `Ord`, so we sort by the raw byte
        // representation explicitly.
        sorted.sort_unstable_by(|a, b| a.as_bytes().cmp(b.as_bytes()));
        let mut hasher = Sha256::new();
        for m in &sorted {
            hasher.update(m.as_ref());
        }
        hasher.update([threshold]);
        let bytes: [u8; 32] = hasher.finalize().into();
        AttestorSetId::from(bytes)
    }
}

// ----- Attestation ------------------------------------------------------------

/// Stored attestation record.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, BorshSerialize, BorshDeserialize)]
#[serde(bound = "S::Address: Serialize + serde::de::DeserializeOwned")]
pub struct Attestation<S: Spec> {
    /// Schema this attestation is bound to. Dictates payload semantics
    /// and which attestor set must have signed.
    pub schema_id: SchemaId,
    /// Caller-computed digest of the off-chain payload. The chain never
    /// sees the plaintext.
    pub payload_hash: PayloadHash,
    /// Address that submitted the attestation. Paid the fee; owns the
    /// record for accounting purposes.
    pub submitter: S::Address,
    /// Unix seconds, sourced from the transaction's block header (not
    /// submitter-provided, to prevent timestamp games).
    pub timestamp: u64,
    /// Quorum signatures over [`SignedAttestationPayload`]. All pubkeys
    /// must be ∈ `schema.attestor_set.members`; count of valid sigs
    /// must be ≥ `schema.attestor_set.threshold`.
    pub signatures: Vec<AttestorSignature>,
}

/// Canonical payload attestors sign over.
///
/// Borsh-encoded, hashed, and signed off-chain by each attestor before
/// the submitter aggregates signatures and submits to the chain.
///
/// Deliberately excludes the [`Attestation::signatures`] field (circular)
/// and any caller-adversarial data. Replay protection comes from the
/// write-once [`AttestationId`] invariant, not from this struct.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, BorshSerialize, BorshDeserialize)]
#[serde(bound = "S::Address: Serialize + serde::de::DeserializeOwned")]
pub struct SignedAttestationPayload<S: Spec> {
    /// See [`Attestation::schema_id`].
    pub schema_id: SchemaId,
    /// See [`Attestation::payload_hash`].
    pub payload_hash: PayloadHash,
    /// See [`Attestation::submitter`].
    pub submitter: S::Address,
    /// See [`Attestation::timestamp`].
    pub timestamp: u64,
}

impl<S: Spec> SignedAttestationPayload<S> {
    /// SHA-256 of the canonical Borsh encoding of this payload.
    ///
    /// This is the digest each attestor signs over. Exposed as a
    /// library helper so attestor quorum software and SDKs don't have
    /// to re-implement the encoding rule.
    pub fn digest(&self) -> Hash32 {
        let bytes = borsh::to_vec(self).expect("Borsh serialization of owned data is infallible");
        Sha256::digest(&bytes).into()
    }
}

// ----- Messages ---------------------------------------------------------------

/// State-changing messages accepted by the attestation module.
///
/// Generic over `S: Spec` because [`CallMessage::RegisterSchema`]
/// carries an optional `fee_routing_addr` of type `S::Address`.
///
/// The SDK's `Module::CallMessage` super-trait requires `UniversalWallet`
/// + `JsonSchema`. We propagate both via macros; the schemars `bound`
/// pulls `S` into scope as a type parameter that itself needs
/// `JsonSchema` (used by the derive's auto-name logic for the generic
/// argument), even though our actual fields only reference `S::Address`.
#[derive(
    Clone,
    Debug,
    PartialEq,
    Eq,
    Serialize,
    Deserialize,
    BorshSerialize,
    BorshDeserialize,
    schemars::JsonSchema,
    sov_modules_api::macros::UniversalWallet,
)]
#[serde(bound = "S::Address: Serialize + serde::de::DeserializeOwned")]
#[schemars(bound = "S: schemars::JsonSchema, S::Address: schemars::JsonSchema")]
pub enum CallMessage<S: Spec> {
    /// Register a new [`AttestorSet`].
    ///
    /// Costs `ATTESTOR_SET_FEE` $LGT (governance, default 10 $LGT).
    /// Derivation: `SHA-256(borsh(members) ‖ threshold)`. Rejected if a
    /// set with the derived id already exists.
    RegisterAttestorSet {
        /// See [`AttestorSet::members`].
        members: Vec<PubKey>,
        /// See [`AttestorSet::threshold`].
        threshold: u8,
    },

    /// Register a new [`Schema`].
    ///
    /// Costs `SCHEMA_REGISTRATION_FEE` $LGT (governance, default 100 $LGT).
    /// Owner is the transaction submitter. `attestor_set` must reference
    /// an already-registered [`AttestorSet`]. `fee_routing_bps` must be
    /// ≤ `MAX_BUILDER_BPS` (5000 in v0). `fee_routing_addr` must be
    /// `Some` iff `fee_routing_bps > 0`.
    RegisterSchema {
        /// See [`Schema::name`].
        name: String,
        /// See [`Schema::version`].
        version: u32,
        /// See [`Schema::attestor_set`].
        attestor_set: AttestorSetId,
        /// See [`Schema::fee_routing_bps`].
        fee_routing_bps: u16,
        /// See [`Schema::fee_routing_addr`].
        fee_routing_addr: Option<S::Address>,
    },

    /// Submit a new [`Attestation`] under an existing schema.
    ///
    /// Costs `ATTESTATION_FEE` $LGT (governance, default 0.001 $LGT),
    /// split per [`Schema::fee_routing_bps`]. Signatures are validated
    /// against the schema's [`AttestorSet`] at submission time.
    SubmitAttestation {
        /// See [`Attestation::schema_id`].
        schema_id: SchemaId,
        /// See [`Attestation::payload_hash`].
        payload_hash: PayloadHash,
        /// See [`Attestation::signatures`].
        signatures: Vec<AttestorSignature>,
    },
}

// ----- Module struct ---------------------------------------------------------

/// The Ligate attestation module.
///
/// Three state fields map 1-to-1 to the three protocol entities:
///
/// - [`AttestationModule::schemas`], `SchemaId → Schema`
/// - [`AttestationModule::attestor_sets`], `AttestorSetId → AttestorSet`
/// - [`AttestationModule::attestations`], `(SchemaId, PayloadHash) → Attestation`
///
/// Call handlers and genesis config live in sibling issues; this struct
/// exists to lock down the state layout that every other piece of the
/// module keys off.
#[derive(Clone, ModuleInfo)]
pub struct AttestationModule<S: Spec> {
    /// Module's own discriminant id. Filled by the SDK from the value
    /// keyed by `ATTESTATION_DISCRIMINANT` in `constants.toml` (21 in
    /// the Ligate canonical assignment).
    #[id]
    pub id: ModuleId,

    /// Reference to the `sov-bank` module. Used to charge `$LGT` fees on
    /// every successful `RegisterAttestorSet`, `RegisterSchema`, and
    /// `SubmitAttestation` call. Bank transfers run before any state
    /// mutation; on `Err` the SDK's tx state unwinds the whole tx.
    #[module]
    pub bank: Bank<S>,

    /// Schema registry: `SchemaId → Schema<S>`.
    #[state]
    pub schemas: StateMap<SchemaId, Schema<S>>,

    /// AttestorSet registry: `AttestorSetId → AttestorSet`.
    #[state]
    pub attestor_sets: StateMap<AttestorSetId, AttestorSet>,

    /// Attestation store: `(SchemaId, PayloadHash) → Attestation<S>`.
    #[state]
    pub attestations: StateMap<AttestationId, Attestation<S>>,

    /// Treasury address, receives the treasury share of every attestation
    /// fee and the full amount of schema / attestor-set registration fees.
    /// Set once at genesis, governance-adjustable later.
    #[state]
    pub treasury: StateValue<S::Address>,

    /// `$LGT` token id used for all attestation-module fee charges.
    ///
    /// Set once at genesis from
    /// [`AttestationConfig::lgt_token_id`]. Identifies the token inside
    /// [`sov_bank::Bank`] that handlers transfer when charging
    /// `attestation_fee`, `schema_registration_fee`, and
    /// `attestor_set_fee`. Immutable after genesis; rotation requires a
    /// chain upgrade.
    ///
    /// `$LGT` is genuinely chain-global; storing it on the attestation
    /// module is pragmatic for v0 because attestation is the only fee
    /// consumer. Extract to a chain-wide config primitive when the second
    /// consumer (Iris relayer module v0.5, `tokens` module v1) lands.
    #[state]
    pub lgt_token_id: StateValue<TokenId>,

    /// Flat per-attestation fee in `$LGT` nanos. Set at genesis.
    /// `Amount` is the bank module's u128 newtype around fee values.
    #[state]
    pub attestation_fee: StateValue<Amount>,

    /// Flat schema-registration fee in `$LGT` nanos. Set at genesis.
    #[state]
    pub schema_registration_fee: StateValue<Amount>,

    /// Flat attestor-set registration fee in `$LGT` nanos. Set at genesis.
    #[state]
    pub attestor_set_fee: StateValue<Amount>,

    /// Running counter of `$LGT` nanos booked to the treasury.
    ///
    /// Accumulates the treasury share of every successful
    /// `SubmitAttestation` plus the full registration fees from
    /// `RegisterAttestorSet` and `RegisterSchema`. Stays in addition to
    /// real bank balances because the cumulative fee-volume signal
    /// diverges from current treasury balance once governance
    /// withdrawals (#41, v1) start spending from the treasury.
    #[state]
    pub total_treasury_collected: StateValue<Amount>,

    /// Running counter of `$LGT` nanos booked per builder address.
    ///
    /// Keyed by `Schema::fee_routing_addr`. Incremented on each
    /// `SubmitAttestation` under a schema with non-zero `fee_routing_bps`
    /// by `total_fee * fee_routing_bps / 10000`. Same audit-trail role
    /// as [`AttestationModule::total_treasury_collected`].
    #[state]
    pub builder_fees_collected: StateMap<S::Address, Amount>,
}

// ----- Protocol constants -----------------------------------------------------

/// Maximum `fee_routing_bps` accepted at schema registration (5000 = 50%).
/// Governance-adjustable in v1+; hardcoded for v0.
pub const MAX_BUILDER_BPS: u16 = 5000;

/// Default attestation fee in $LGT, in the chain's smallest unit.
/// Placeholder constant. Real fee sizing is a governance parameter set
/// at launch. Documented here for reference against the spec.
///
/// `$LGT` uses **9 decimals** (Solana lamport convention). The smallest
/// representable unit is `1 nano` = `0.000000001 $LGT`. The new SDK
/// uses [`sov_bank::Amount`] (a `u128` newtype) for token amounts;
/// our defaults still fit comfortably in `u64`, but using `Amount`
/// for state values + helpers keeps types aligned with bank.
pub const DEFAULT_ATTESTATION_FEE_LGT_NANOS: Amount = Amount::new(1_000_000); // 0.001 $LGT

/// Default schema-registration fee. 100 $LGT at 9 decimals.
pub const DEFAULT_SCHEMA_REGISTRATION_FEE_LGT_NANOS: Amount = Amount::new(100_000_000_000);

/// Default attestor-set registration fee. 10 $LGT at 9 decimals.
pub const DEFAULT_ATTESTOR_SET_FEE_LGT_NANOS: Amount = Amount::new(10_000_000_000);

// ============================================================================
// Genesis configuration
// ============================================================================

/// An attestor set declared in the genesis config.
///
/// Validated with the same rules as [`CallMessage::RegisterAttestorSet`]:
/// non-empty members, `1 <= threshold <= members.len()`, derived id must
/// not collide with another attestor set already registered at genesis
/// time.
#[derive(Clone, Debug, Serialize, Deserialize, BorshSerialize, BorshDeserialize)]
pub struct InitialAttestorSet {
    /// Attestor public keys.
    pub members: Vec<PubKey>,
    /// M-of-N threshold.
    pub threshold: u8,
}

/// A schema declared in the genesis config.
///
/// Validated with the same rules as [`CallMessage::RegisterSchema`]: the
/// referenced attestor set must be known (either declared in
/// [`AttestationConfig::initial_attestor_sets`] or registered earlier in
/// the genesis flow), `fee_routing_bps <= MAX_BUILDER_BPS`, and the
/// address / bps orphan check. `owner` is supplied explicitly at genesis
/// because there is no transaction sender at that point.
#[derive(Clone, Debug, Serialize, Deserialize, BorshSerialize, BorshDeserialize)]
#[serde(bound = "S::Address: Serialize + serde::de::DeserializeOwned")]
pub struct InitialSchema<S: Spec> {
    /// Owner address assigned on-chain.
    pub owner: S::Address,
    /// Schema name, e.g. `"themisra.proof-of-prompt"`.
    pub name: String,
    /// Monotonic version; bumping it creates a new schema.
    pub version: u32,
    /// [`AttestorSetId`] the schema binds to.
    pub attestor_set: AttestorSetId,
    /// Fee routing basis points (`0..=MAX_BUILDER_BPS`).
    pub fee_routing_bps: u16,
    /// Fee routing address; required iff `fee_routing_bps > 0`.
    pub fee_routing_addr: Option<S::Address>,
}

/// Genesis configuration loaded once at chain launch.
///
/// Operators supply one of these, typically as a JSON blob, via the
/// genesis ceremony. See `docs/development/devnet.md` for the operator
/// flow and `crates/modules/attestation/examples/genesis.example.json`
/// for a worked example.
#[derive(Clone, Debug, Serialize, Deserialize, BorshSerialize, BorshDeserialize)]
#[serde(bound = "S::Address: Serialize + serde::de::DeserializeOwned")]
pub struct AttestationConfig<S: Spec> {
    /// Address that will receive treasury fee flows. Must be set
    /// explicitly in real configs; only test scaffolding should rely
    /// on a default value.
    pub treasury: S::Address,
    /// `$LGT` [`TokenId`] inside `sov-bank` used for every fee charge.
    ///
    /// In the new SDK, `TokenId`s are explicit at genesis (no
    /// `(name, salt)` derivation), so this value is taken verbatim
    /// from the bank's gas-token config. The validator in
    /// `crates/stf/src/genesis_config.rs` cross-checks that this
    /// matches the bank's gas-token id.
    pub lgt_token_id: TokenId,
    /// Flat per-attestation fee in `$LGT` nanos (9 decimals).
    pub attestation_fee: Amount,
    /// Flat schema-registration fee in `$LGT` nanos.
    pub schema_registration_fee: Amount,
    /// Flat attestor-set registration fee in `$LGT` nanos.
    pub attestor_set_fee: Amount,
    /// Attestor sets to register at genesis, in order.
    pub initial_attestor_sets: Vec<InitialAttestorSet>,
    /// Schemas to register at genesis, in order. Each schema's
    /// `attestor_set` must be one registered earlier in the flow (either
    /// in `initial_attestor_sets` above, or by a previous `InitialSchema`
    /// bootstrap pass, though the latter is not supported today).
    pub initial_schemas: Vec<InitialSchema<S>>,
}

// ============================================================================
// Errors
// ============================================================================

/// Typed errors produced by the attestation module's call handlers.
///
/// These convert into [`sov_modules_api::Error`] (via [`anyhow::Error`]) when
/// returned from a Module handler, so callers of the RPC can pattern-match
/// on the wire shape while the chain runtime stays generic.
#[derive(Debug, ThisError)]
pub enum AttestationError {
    /// `threshold` was greater than the number of supplied members.
    #[error("attestor set threshold ({threshold}) exceeds member count ({count})")]
    ThresholdExceedsMembers {
        /// Supplied threshold.
        threshold: u8,
        /// Number of members supplied.
        count: usize,
    },

    /// A threshold of 0 was supplied, which would accept attestations with no
    /// signatures.
    #[error("attestor set threshold must be at least 1")]
    ZeroThreshold,

    /// Members list was empty.
    #[error("attestor set must have at least one member")]
    EmptyAttestorSet,

    /// An attestor set with this derived id already exists.
    #[error("attestor set already registered")]
    DuplicateAttestorSet,

    /// A schema with this derived id already exists (same owner, name, version).
    #[error("schema already registered")]
    DuplicateSchema,

    /// Schema registration referenced an [`AttestorSetId`] that isn't stored.
    #[error("schema references an unregistered attestor set")]
    UnknownAttestorSet,

    /// `fee_routing_bps` exceeded the protocol cap [`MAX_BUILDER_BPS`].
    #[error("fee routing bps ({bps}) exceeds protocol cap ({cap})")]
    FeeRoutingExceedsCap {
        /// Supplied basis points.
        bps: u16,
        /// Protocol cap (v0: 5000 = 50%).
        cap: u16,
    },

    /// Fee routing was misconfigured: address set without basis points, or
    /// basis points > 0 without an address.
    #[error(
        "fee routing misconfigured: address and basis points must be set together or both absent"
    )]
    OrphanFeeRouting,

    /// Submission referenced a [`SchemaId`] that isn't stored.
    #[error("schema not found")]
    UnknownSchema,

    /// An attestation with this `(schema_id, payload_hash)` already exists.
    #[error("attestation already exists for this (schema_id, payload_hash)")]
    DuplicateAttestation,

    /// The same pubkey appeared twice in one submission's signatures vector.
    #[error("duplicate attestor pubkey in signatures")]
    DuplicateSignaturePubkey,

    /// A signature's pubkey was not a member of the schema's attestor set.
    #[error("signature pubkey is not in the schema's attestor set")]
    UnknownAttestorPubkey,

    /// A signature's pubkey bytes did not decode as a valid ed25519 point.
    #[error("signature pubkey is not a valid ed25519 point")]
    InvalidAttestorPubkey,

    /// A signature's raw bytes were not the 64 bytes ed25519 expects.
    #[error("signature length {actual} != expected 64 for ed25519")]
    BadSignatureLength {
        /// Length that was actually submitted.
        actual: usize,
    },

    /// A signature did not verify against the canonical attestation digest.
    #[error("signature did not verify against attestation digest")]
    InvalidSignature,

    /// Fewer valid signatures than the schema's attestor set requires.
    #[error("quorum not met: {provided} valid signatures, need {required}")]
    BelowThreshold {
        /// Count of valid signatures in the submission.
        provided: u8,
        /// Threshold required by the schema's attestor set.
        required: u8,
    },

    /// A schema referenced an attestor set that no longer exists at submit
    /// time. Should be unreachable given the register-time invariants, but
    /// surfaced as an explicit error to keep state-transition code honest.
    #[error("schema's attestor set is missing from state")]
    MissingAttestorSet,

    /// `lgt_token_address` or `treasury` was not set at genesis. Indicates
    /// a misconfigured chain. Should be unreachable for a chain that ran
    /// `Module::genesis` cleanly, but surfaced as an error so handlers
    /// fail honestly instead of panicking.
    #[error("attestation module not initialised: missing $LGT token address or treasury")]
    ChainNotConfigured,
}

// ============================================================================
// Module implementation
// ============================================================================

/// Event type emitted by the attestation module.
///
/// Reserved for v0; the module's externally interesting state changes
/// are already captured in the `attestations` map and queryable via
/// RPC. We carry the typed enum (rather than `()`) because the SDK's
/// `Module` trait requires `Event: BorshSerialize + BorshDeserialize +
/// JsonSchema + Send + Sync + 'static + PartialEq + Debug`, and to leave
/// space for typed events when the module grows them. Adding new
/// variants here is non-breaking.
#[derive(Clone, Debug, PartialEq, Eq, BorshSerialize, BorshDeserialize, schemars::JsonSchema)]
pub enum AttestationEvent {
    /// Placeholder variant. Never emitted in v0; reserved so the enum
    /// is non-empty (Borsh derives require at least one variant on
    /// enums) without committing to an event shape we'd later
    /// regret. Real events land alongside the query RPC in #21.
    #[doc(hidden)]
    Reserved,
}

impl<S: Spec> Module for AttestationModule<S> {
    type Spec = S;
    type Config = AttestationConfig<S>;
    type CallMessage = CallMessage<S>;
    type Event = AttestationEvent;
    type Error = anyhow::Error;

    fn genesis(
        &mut self,
        _genesis_rollup_header: &<<S as Spec>::Da as DaSpec>::BlockHeader,
        config: &Self::Config,
        state: &mut impl GenesisState<S>,
    ) -> anyhow::Result<()> {
        self.seed_from_config(config, state)
    }

    fn call(
        &mut self,
        msg: Self::CallMessage,
        context: &Context<Self::Spec>,
        state: &mut impl TxState<S>,
    ) -> Result<(), Self::Error> {
        match msg {
            CallMessage::RegisterAttestorSet { members, threshold } => {
                self.handle_register_attestor_set(members, threshold, context, state)
            }
            CallMessage::RegisterSchema {
                name,
                version,
                attestor_set,
                fee_routing_bps,
                fee_routing_addr,
            } => self.handle_register_schema(
                name,
                version,
                attestor_set,
                fee_routing_bps,
                fee_routing_addr,
                context,
                state,
            ),
            CallMessage::SubmitAttestation {
                schema_id,
                payload_hash,
                signatures,
            } => self.handle_submit_attestation(schema_id, payload_hash, signatures, context, state),
        }
    }
}

impl<S: Spec> AttestationModule<S> {
    /// Apply an [`AttestationConfig`] during [`Module::genesis`].
    ///
    /// Stores treasury and fee parameters in state, then registers each
    /// configured attestor set and schema with the same validation rules
    /// the `RegisterAttestorSet` and `RegisterSchema` handlers use at
    /// runtime. Rejects duplicates and orphan / over-cap fee routing.
    ///
    /// Genesis bypasses fee charging by writing directly to state: there
    /// is no transaction sender at genesis to charge from. Fees apply
    /// only to user txs after the chain is live.
    fn seed_from_config(
        &mut self,
        config: &AttestationConfig<S>,
        state: &mut impl GenesisState<S>,
    ) -> anyhow::Result<()> {
        self.treasury.set(&config.treasury, state)?;
        self.lgt_token_id.set(&config.lgt_token_id, state)?;
        self.attestation_fee.set(&config.attestation_fee, state)?;
        self.schema_registration_fee.set(&config.schema_registration_fee, state)?;
        self.attestor_set_fee.set(&config.attestor_set_fee, state)?;

        for initial in &config.initial_attestor_sets {
            if initial.members.is_empty() {
                return Err(AttestationError::EmptyAttestorSet.into());
            }
            if initial.threshold == 0 {
                return Err(AttestationError::ZeroThreshold.into());
            }
            if usize::from(initial.threshold) > initial.members.len() {
                return Err(AttestationError::ThresholdExceedsMembers {
                    threshold: initial.threshold,
                    count: initial.members.len(),
                }
                .into());
            }

            let mut sorted_members = initial.members.clone();
            sorted_members.sort_unstable_by(|a, b| a.as_bytes().cmp(b.as_bytes()));

            let id = AttestorSet::derive_id(&sorted_members, initial.threshold);
            if self.attestor_sets.get(&id, state)?.is_some() {
                return Err(AttestationError::DuplicateAttestorSet.into());
            }
            self.attestor_sets.set(
                &id,
                &AttestorSet { members: sorted_members, threshold: initial.threshold },
                state,
            )?;
        }

        for schema in &config.initial_schemas {
            if schema.fee_routing_bps > MAX_BUILDER_BPS {
                return Err(AttestationError::FeeRoutingExceedsCap {
                    bps: schema.fee_routing_bps,
                    cap: MAX_BUILDER_BPS,
                }
                .into());
            }
            if (schema.fee_routing_bps > 0) != schema.fee_routing_addr.is_some() {
                return Err(AttestationError::OrphanFeeRouting.into());
            }
            if self.attestor_sets.get(&schema.attestor_set, state)?.is_none() {
                return Err(AttestationError::UnknownAttestorSet.into());
            }

            let id = Schema::<S>::derive_id(&schema.owner, &schema.name, schema.version);
            if self.schemas.get(&id, state)?.is_some() {
                return Err(AttestationError::DuplicateSchema.into());
            }
            self.schemas.set(
                &id,
                &Schema {
                    owner: schema.owner.clone(),
                    name: schema.name.clone(),
                    version: schema.version,
                    attestor_set: schema.attestor_set,
                    fee_routing_bps: schema.fee_routing_bps,
                    fee_routing_addr: schema.fee_routing_addr.clone(),
                },
                state,
            )?;
        }

        Ok(())
    }

    /// Handle [`CallMessage::RegisterAttestorSet`].
    fn handle_register_attestor_set(
        &mut self,
        members: Vec<PubKey>,
        threshold: u8,
        context: &Context<S>,
        state: &mut impl TxState<S>,
    ) -> anyhow::Result<()> {
        if members.is_empty() {
            return Err(AttestationError::EmptyAttestorSet.into());
        }
        if threshold == 0 {
            return Err(AttestationError::ZeroThreshold.into());
        }
        if usize::from(threshold) > members.len() {
            return Err(AttestationError::ThresholdExceedsMembers {
                threshold,
                count: members.len(),
            }
            .into());
        }

        // Store members in sorted order so later reads match the id derivation.
        let mut sorted_members = members;
        sorted_members.sort_unstable_by(|a, b| a.as_bytes().cmp(b.as_bytes()));

        let id = AttestorSet::derive_id(&sorted_members, threshold);
        if self.attestor_sets.get(&id, state)?.is_some() {
            return Err(AttestationError::DuplicateAttestorSet.into());
        }

        // Charge the registration fee after validation and duplicate
        // check, before state mutation. If the submitter has insufficient
        // `$LGT`, the bank transfer returns `Err`, the tx state unwinds,
        // and the whole tx fails atomically.
        let fee = self.attestor_set_fee.get(state)?.unwrap_or(DEFAULT_ATTESTOR_SET_FEE_LGT_NANOS);
        self.charge_to_treasury(context.sender(), fee, state)?;

        self.attestor_sets.set(
            &id,
            &AttestorSet { members: sorted_members, threshold },
            state,
        )?;

        Ok(())
    }

    /// Handle [`CallMessage::RegisterSchema`].
    #[allow(clippy::too_many_arguments)]
    fn handle_register_schema(
        &mut self,
        name: String,
        version: u32,
        attestor_set: AttestorSetId,
        fee_routing_bps: u16,
        fee_routing_addr: Option<S::Address>,
        context: &Context<S>,
        state: &mut impl TxState<S>,
    ) -> anyhow::Result<()> {
        if fee_routing_bps > MAX_BUILDER_BPS {
            return Err(AttestationError::FeeRoutingExceedsCap {
                bps: fee_routing_bps,
                cap: MAX_BUILDER_BPS,
            }
            .into());
        }
        if (fee_routing_bps > 0) != fee_routing_addr.is_some() {
            return Err(AttestationError::OrphanFeeRouting.into());
        }
        if self.attestor_sets.get(&attestor_set, state)?.is_none() {
            return Err(AttestationError::UnknownAttestorSet.into());
        }

        let owner: S::Address = context.sender().clone();
        let id = Schema::<S>::derive_id(&owner, &name, version);

        if self.schemas.get(&id, state)?.is_some() {
            return Err(AttestationError::DuplicateSchema.into());
        }

        // Charge the registration fee after validation and duplicate
        // check, before state mutation. Insufficient balance → `Err`,
        // tx state unwinds, no state changes.
        let fee = self
            .schema_registration_fee
            .get(state)?
            .unwrap_or(DEFAULT_SCHEMA_REGISTRATION_FEE_LGT_NANOS);
        self.charge_to_treasury(context.sender(), fee, state)?;

        self.schemas.set(
            &id,
            &Schema { owner, name, version, attestor_set, fee_routing_bps, fee_routing_addr },
            state,
        )?;

        Ok(())
    }

    /// Handle [`CallMessage::SubmitAttestation`].
    ///
    /// Enforces:
    /// 1. Schema exists.
    /// 2. `(schema_id, payload_hash)` has not been written before.
    /// 3. Every signature is valid ed25519 over the canonical
    ///    [`SignedAttestationPayload`] digest.
    /// 4. Every signing pubkey is a member of the schema's [`AttestorSet`].
    /// 5. No pubkey appears twice in the submission.
    /// 6. Count of valid signatures is at least the attestor set's
    ///    `threshold`.
    ///
    /// Fees are charged BEFORE the attestation is written; failure of
    /// either the treasury or builder transfer aborts the tx via the
    /// SDK's TxState unwind.
    fn handle_submit_attestation(
        &mut self,
        schema_id: SchemaId,
        payload_hash: PayloadHash,
        signatures: Vec<AttestorSignature>,
        context: &Context<S>,
        state: &mut impl TxState<S>,
    ) -> anyhow::Result<()> {
        let schema = self
            .schemas
            .get(&schema_id, state)?
            .ok_or(AttestationError::UnknownSchema)?;

        let attestation_id = AttestationId::from_pair(&schema_id, &payload_hash);
        if self.attestations.get(&attestation_id, state)?.is_some() {
            return Err(AttestationError::DuplicateAttestation.into());
        }

        let attestor_set = self
            .attestor_sets
            .get(&schema.attestor_set, state)?
            .ok_or(AttestationError::MissingAttestorSet)?;

        let submitter: S::Address = context.sender().clone();
        // TODO: pull the real block timestamp once the runtime exposes
        // a slot/header view to handlers. For now, attestations carry
        // `timestamp = 0`; the write-once key prevents replay either way.
        let timestamp = 0u64;

        // Canonical digest attestors sign over. Must be computed after
        // we know `submitter` and `timestamp`; those are part of what's
        // signed.
        let digest = SignedAttestationPayload::<S> {
            schema_id,
            payload_hash,
            submitter: submitter.clone(),
            timestamp,
        }
        .digest();

        validate_signatures(&signatures, &attestor_set, &digest)?;

        // Charge the attestation fee BEFORE writing the attestation.
        // Split per `schema.fee_routing_bps`: builder share goes to
        // `schema.fee_routing_addr` (if configured), remainder to the
        // treasury. Two transfers (treasury then builder) so a partial
        // failure unwinds both via the SDK's TxState.
        let total_fee = self
            .attestation_fee
            .get(state)?
            .unwrap_or(DEFAULT_ATTESTATION_FEE_LGT_NANOS);
        let (builder_share, treasury_share) =
            split_attestation_fee(total_fee, schema.fee_routing_bps);
        self.charge_to_treasury(context.sender(), treasury_share, state)?;
        if let Some(addr) = &schema.fee_routing_addr {
            if builder_share != Amount::ZERO {
                self.charge_to_builder(context.sender(), addr, builder_share, state)?;
            }
        }

        self.attestations.set(
            &attestation_id,
            &Attestation { schema_id, payload_hash, submitter, timestamp, signatures },
            state,
        )?;

        Ok(())
    }

    /// Move `amount` `$LGT` nanos from `submitter` to the treasury via
    /// `sov-bank`, then bump the cumulative
    /// [`AttestationModule::total_treasury_collected`] counter.
    ///
    /// Returns `Ok(())` for `amount == 0` without touching the bank or
    /// counter, so callers don't need to special-case zero-fee paths.
    /// Bumps the counter only after a successful transfer; the SDK's
    /// `TxState` unwind handles the failure case (no half-state).
    fn charge_to_treasury(
        &mut self,
        submitter: &S::Address,
        amount: Amount,
        state: &mut impl TxState<S>,
    ) -> anyhow::Result<()> {
        if amount == Amount::ZERO {
            return Ok(());
        }
        let lgt_token_id =
            self.lgt_token_id.get(state)?.ok_or(AttestationError::ChainNotConfigured)?;
        let treasury =
            self.treasury.get(state)?.ok_or(AttestationError::ChainNotConfigured)?;
        self.bank.transfer_from(
            submitter,
            &treasury,
            Coins { amount, token_id: lgt_token_id },
            state,
        )?;
        self.add_to_treasury(amount, state)?;
        Ok(())
    }

    /// Move `amount` `$LGT` nanos from `submitter` to `builder_addr` via
    /// `sov-bank`, then bump the cumulative
    /// [`AttestationModule::builder_fees_collected`] counter for that
    /// address. Same `amount == 0` short-circuit and same atomicity
    /// guarantees as [`Self::charge_to_treasury`].
    fn charge_to_builder(
        &mut self,
        submitter: &S::Address,
        builder_addr: &S::Address,
        amount: Amount,
        state: &mut impl TxState<S>,
    ) -> anyhow::Result<()> {
        if amount == Amount::ZERO {
            return Ok(());
        }
        let lgt_token_id =
            self.lgt_token_id.get(state)?.ok_or(AttestationError::ChainNotConfigured)?;
        self.bank.transfer_from(
            submitter,
            builder_addr,
            Coins { amount, token_id: lgt_token_id },
            state,
        )?;
        self.add_to_builder(builder_addr, amount, state)?;
        Ok(())
    }

    /// Increment [`AttestationModule::total_treasury_collected`] by `amount`,
    /// saturating at `Amount::MAX` (i.e. `u128::MAX`).
    fn add_to_treasury(
        &mut self,
        amount: Amount,
        state: &mut impl TxState<S>,
    ) -> anyhow::Result<()> {
        let current = self.total_treasury_collected.get(state)?.unwrap_or(Amount::new(0));
        self.total_treasury_collected.set(&current.saturating_add(amount), state)?;
        Ok(())
    }

    /// Increment [`AttestationModule::builder_fees_collected`] for `addr` by
    /// `amount`, saturating at `Amount::MAX`.
    fn add_to_builder(
        &mut self,
        addr: &S::Address,
        amount: Amount,
        state: &mut impl TxState<S>,
    ) -> anyhow::Result<()> {
        let current =
            self.builder_fees_collected.get(addr, state)?.unwrap_or(Amount::new(0));
        self.builder_fees_collected
            .set(addr, &current.saturating_add(amount), state)?;
        Ok(())
    }
}

/// Split an attestation fee into `(builder_share, treasury_share)` per
/// `fee_routing_bps` (basis points, capped at [`MAX_BUILDER_BPS`]).
///
/// `Amount` is a `u128` newtype. The intermediate split is computed as
/// `total / 10_000 * bps + (total % 10_000) * bps / 10_000` to keep the
/// multiplication well below `u128::MAX` even when `total` is itself
/// near the max.
fn split_attestation_fee(total: Amount, bps: u16) -> (Amount, Amount) {
    let total_u128 = total.0;
    let bps_u128 = u128::from(bps);
    let builder_u128 = total_u128 / 10_000 * bps_u128 + (total_u128 % 10_000) * bps_u128 / 10_000;
    let builder = Amount::new(builder_u128);
    let treasury = Amount::new(total_u128.saturating_sub(builder_u128));
    (builder, treasury)
}

/// Validate a submission's [`AttestorSignature`] vector against an
/// [`AttestorSet`] and the canonical attestation digest.
///
/// Enforces, in order:
/// 1. No duplicate pubkey within the submission.
/// 2. Each pubkey is a member of `set.members`.
/// 3. Each pubkey bytes decode as a valid ed25519 point.
/// 4. Each signature's raw bytes are 64 bytes long.
/// 5. The ed25519 signature verifies against `digest` for its pubkey.
/// 6. The count of valid signatures is at least `set.threshold`.
///
/// Ed25519 is the only scheme accepted in v0. BLS aggregates or other
/// schemes would be added as separate variants later; `AttestorSignature.sig`
/// is `Vec<u8>` today precisely to leave room for that.
fn validate_signatures(
    signatures: &[AttestorSignature],
    set: &AttestorSet,
    digest: &Hash32,
) -> anyhow::Result<()> {
    use std::collections::HashSet;

    use ed25519_dalek::{Signature, Verifier, VerifyingKey};

    let members: HashSet<PubKey> = set.members.iter().copied().collect();
    let mut seen: HashSet<PubKey> = HashSet::new();
    let mut valid: u16 = 0;

    for attested in signatures {
        if !seen.insert(attested.pubkey) {
            return Err(AttestationError::DuplicateSignaturePubkey.into());
        }

        if !members.contains(&attested.pubkey) {
            return Err(AttestationError::UnknownAttestorPubkey.into());
        }

        let verifying_key = VerifyingKey::from_bytes(attested.pubkey.as_bytes())
            .map_err(|_| AttestationError::InvalidAttestorPubkey)?;

        let sig_bytes: [u8; 64] = attested
            .sig
            .as_slice()
            .try_into()
            .map_err(|_| AttestationError::BadSignatureLength { actual: attested.sig.len() })?;
        let signature = Signature::from_bytes(&sig_bytes);

        if verifying_key.verify(digest, &signature).is_err() {
            return Err(AttestationError::InvalidSignature.into());
        }

        valid = valid.saturating_add(1);
    }

    let valid_u8: u8 = valid.min(u16::from(u8::MAX)) as u8;
    if valid_u8 < set.threshold {
        return Err(AttestationError::BelowThreshold {
            provided: valid_u8,
            required: set.threshold,
        }
        .into());
    }

    Ok(())
}

// ============================================================================
// Tests
// ============================================================================

