//! Genesis configuration assembly.
//!
//! The runtime's [`GenesisConfig`] type is derive-generated by the
//! `Genesis` macro (one field per module). This module is responsible
//! for taking a directory of per-module JSON files and producing that
//! aggregate config, plus a small validator that catches obvious
//! cross-module misconfigurations before genesis runs.
//!
//! Layout of the JSON directory ([`GenesisPaths::from_dir`] expects):
//!
//! ```text
//! <dir>/
//!   bank.json                 # sov_bank::BankConfig
//!   accounts.json             # sov_accounts::AccountConfig
//!   sequencer_registry.json   # sov_sequencer_registry::SequencerConfig
//!   attestation.json          # attestation::AttestationConfig
//! ```
//!
//! Per-module schemas are documented next to their respective configs.
//! See `devnet/genesis/` in the rollup binary's PR (Phase A.2) for a
//! worked example.
//!
//! [`GenesisConfig`]: crate::runtime::GenesisConfig

use std::path::{Path, PathBuf};

use anyhow::{bail, Context as _};
use sov_accounts::AccountConfig;
use sov_bank::BankConfig;
use sov_modules_api::Context;
use sov_modules_stf_blueprint::Runtime as RuntimeTrait;
use sov_rollup_interface::da::DaSpec;
use sov_sequencer_registry::SequencerConfig;
use sov_stf_runner::read_json_file;

use crate::runtime::{GenesisConfig, Runtime};

/// Filesystem layout for per-module genesis JSON files.
///
/// Construct via [`GenesisPaths::from_dir`] for the conventional
/// layout, or set fields manually if your operator workflow places
/// configs elsewhere (e.g. CI fixtures).
pub struct GenesisPaths {
    /// `sov_bank::BankConfig` JSON.
    pub bank_genesis_path: PathBuf,
    /// `sov_accounts::AccountConfig` JSON.
    pub accounts_genesis_path: PathBuf,
    /// `sov_sequencer_registry::SequencerConfig` JSON.
    pub sequencer_genesis_path: PathBuf,
    /// `attestation::AttestationConfig` JSON. Spec'd in
    /// `docs/development/genesis.example.json` at the repo root.
    pub attestation_genesis_path: PathBuf,
}

impl GenesisPaths {
    /// Conventional layout: a directory holding `bank.json`,
    /// `accounts.json`, `sequencer_registry.json`, and
    /// `attestation.json`.
    pub fn from_dir(dir: impl AsRef<Path>) -> Self {
        let dir = dir.as_ref();
        Self {
            bank_genesis_path: dir.join("bank.json"),
            accounts_genesis_path: dir.join("accounts.json"),
            sequencer_genesis_path: dir.join("sequencer_registry.json"),
            attestation_genesis_path: dir.join("attestation.json"),
        }
    }
}

/// Read every per-module config file and assemble the runtime's
/// [`GenesisConfig`], with cross-module validation applied.
pub fn get_genesis_config<C: Context, Da: DaSpec>(
    genesis_paths: &GenesisPaths,
) -> Result<<Runtime<C, Da> as RuntimeTrait<C, Da>>::GenesisConfig, anyhow::Error> {
    let genesis_config =
        create_genesis_config(genesis_paths).context("Unable to read genesis configuration")?;
    validate_config(genesis_config)
}

/// Cross-module sanity checks applied after individual configs deserialise.
///
/// Right now we enforce one invariant: the address `sequencer_registry`
/// uses to lock sequencer collateral must be the genesis `$LGT` token
/// address, otherwise a registered sequencer can never satisfy the
/// lock requirement. The check rebuilds the deterministic token
/// address from `bank.tokens[0]` (which by convention is `$LGT`,
/// `salt = 0`) and compares against `sequencer_registry.coins_to_lock`.
///
/// More invariants land here as the runtime grows. Examples we'll
/// likely add: attestation's `lgt_token_address` must equal the same
/// derived `$LGT` address; attestation's `treasury` must be a valid
/// account with a bank entry. Out of scope for Phase A.1.
pub(crate) fn validate_config<C: Context, Da: DaSpec>(
    genesis_config: <Runtime<C, Da> as RuntimeTrait<C, Da>>::GenesisConfig,
) -> Result<<Runtime<C, Da> as RuntimeTrait<C, Da>>::GenesisConfig, anyhow::Error> {
    if genesis_config.bank.tokens.is_empty() {
        bail!("bank genesis must declare at least one token (the chain's gas token)");
    }
    let lgt_token_address = sov_bank::get_genesis_token_address::<C>(
        &genesis_config.bank.tokens[0].token_name,
        genesis_config.bank.tokens[0].salt,
    );
    let coins_token_addr = &genesis_config.sequencer_registry.coins_to_lock.token_address;
    if coins_token_addr != &lgt_token_address {
        bail!(
            "sequencer_registry.coins_to_lock.token_address mismatches the genesis $LGT token: \
             expected {} (derived from bank.tokens[0]), got {}",
            lgt_token_address,
            coins_token_addr
        );
    }
    Ok(genesis_config)
}

fn create_genesis_config<C: Context, Da: DaSpec>(
    genesis_paths: &GenesisPaths,
) -> anyhow::Result<<Runtime<C, Da> as RuntimeTrait<C, Da>>::GenesisConfig> {
    let bank_config: BankConfig<C> = read_json_file(&genesis_paths.bank_genesis_path)?;
    let accounts_config: AccountConfig<C> = read_json_file(&genesis_paths.accounts_genesis_path)?;
    let sequencer_registry_config: SequencerConfig<C, Da> =
        read_json_file(&genesis_paths.sequencer_genesis_path)?;
    let attestation_config: attestation::AttestationConfig =
        read_json_file(&genesis_paths.attestation_genesis_path)?;

    Ok(GenesisConfig::new(
        bank_config,
        accounts_config,
        sequencer_registry_config,
        attestation_config,
    ))
}
