//! Genesis configuration assembly.
//!
//! WIP scaffold for Phase A.2.1 of #13. The runtime's
//! [`crate::GenesisConfig`] type is derive-generated by the
//! `Genesis` macro (one field per module). This module will hold:
//!
//! - `GenesisPaths`: per-module JSON file paths that an operator
//!   supplies at chain bringup.
//! - `create_genesis_config<S>(&GenesisPaths) -> Result<GenesisConfig<S>>`:
//!   reads each JSON file, deserialises into the matching module's
//!   `*Config` type, returns the aggregate.
//! - `validate_config<S>(&GenesisConfig<S>)`: cross-module
//!   invariants (e.g. attestation's `lgt_token_id` must match the
//!   gas-token id from `bank.gas_token_config`).
//!
//! Land on the next commit. Stubbed here so the parent module
//! compiles.

#![allow(dead_code)]

use std::path::{Path, PathBuf};

/// Per-module genesis JSON file paths.
///
/// Convention: a single directory holds one JSON per module, named
/// `<module>.json`. [`GenesisPaths::from_dir`] expands a directory
/// path into the full set.
#[derive(Clone, Debug)]
pub struct GenesisPaths {
    /// `sov_bank::BankConfig` JSON.
    pub bank: PathBuf,
    /// `sov_accounts::AccountConfig` JSON.
    pub accounts: PathBuf,
    /// `sov_sequencer_registry::SequencerRegistryConfig` JSON.
    pub sequencer_registry: PathBuf,
    /// `sov_operator_incentives::OperatorIncentivesConfig` JSON.
    pub operator_incentives: PathBuf,
    /// `sov_attester_incentives::AttesterIncentivesConfig` JSON.
    pub attester_incentives: PathBuf,
    /// `sov_prover_incentives::ProverIncentivesConfig` JSON.
    pub prover_incentives: PathBuf,
    /// `sov_chain_state::ChainStateConfig` JSON.
    pub chain_state: PathBuf,
    /// `attestation::AttestationConfig` JSON.
    pub attestation: PathBuf,
}

impl GenesisPaths {
    /// Conventional layout: a directory holding `bank.json`,
    /// `accounts.json`, etc.
    pub fn from_dir(dir: impl AsRef<Path>) -> Self {
        let dir = dir.as_ref();
        Self {
            bank: dir.join("bank.json"),
            accounts: dir.join("accounts.json"),
            sequencer_registry: dir.join("sequencer_registry.json"),
            operator_incentives: dir.join("operator_incentives.json"),
            attester_incentives: dir.join("attester_incentives.json"),
            prover_incentives: dir.join("prover_incentives.json"),
            chain_state: dir.join("chain_state.json"),
            attestation: dir.join("attestation.json"),
        }
    }
}
