//! `Runtime` trait wiring for the rollup binary.
//!
//! [`crate::runtime::Runtime`] is the runtime newtype around the
//! declaration crate's [`RuntimeInner`]. This module implements the
//! three traits the SDK's STF blueprint needs to actually drive the
//! runtime against blocks:
//!
//! - [`sov_modules_api::Runtime`]: top-level wiring — `CHAIN_HASH`,
//!   `Auth`, `GenesisConfig`, `endpoints`. Glues the per-module
//!   derives together into a node-runnable surface.
//! - [`HasCapabilities`]: surfaces the bundle of modules the
//!   STF/sequencer use during slot processing (bank for fees,
//!   sequencer-registry for blob auth, accounts for nonces, etc.).
//!   We use the SDK's [`StandardProvenRollupCapabilities`] with no
//!   gas payer — `sov-paymaster` is omitted from the runtime.
//! - [`HasKernel`]: chooses the slot-processing kernel. We pick
//!   [`SoftConfirmationsKernel`] (process all blobs in DA order;
//!   match the SDK demo's default).
//!
//! ## `CHAIN_HASH`
//!
//! Generated at build time (`build.rs`) by hashing the runtime's
//! universal-wallet schema. Every signed transaction binds to this
//! hash; clients on a different runtime composition produce
//! signatures that fail validation. See [`__generated`] for the
//! file the build script writes.
//!
//! [`HasCapabilities`]: sov_modules_api::capabilities::HasCapabilities
//! [`HasKernel`]: sov_modules_api::capabilities::HasKernel
//! [`RuntimeInner`]: ligate_stf_declaration::Runtime

use std::sync::Arc;

use sov_address::{EthereumAddress, FromVmAddress};
use sov_capabilities::StandardProvenRollupCapabilities;
use sov_kernels::soft_confirmations::SoftConfirmationsKernel;
use sov_modules_api::capabilities::{
    Guard, HasCapabilities, HasKernel, KernelWithSlotMapping, RollupAuthenticator,
};
use sov_modules_api::rest::{ApiState, HasRestApi};
use sov_modules_api::sov_universal_wallet::schema::Schema;
use sov_modules_api::{NodeEndpoints, OperatingMode, Spec};
use sov_rollup_apis::endpoints::dedup::{DeDupEndpoint, SovereignDeDupEndpoint};
use sov_rollup_apis::endpoints::schema::{SchemaEndpoint, StandardSchemaEndpoint};

use crate::genesis_config::{create_genesis_config, GenesisPaths};
use crate::runtime::{GenesisConfig, Runtime};

/// Build-script-generated artifacts: the runtime's `CHAIN_HASH`,
/// borsh schema, and JSON schema. Written to `OUT_DIR/autogenerated.rs`
/// by `build.rs` on every build of this crate.
#[allow(missing_docs)]
pub mod __generated {
    include!(concat!(env!("OUT_DIR"), "/autogenerated.rs"));
}

impl<S: Spec> sov_modules_api::Runtime<S> for Runtime<S>
where
    S::Address: FromVmAddress<EthereumAddress>,
{
    const CHAIN_HASH: [u8; 32] = __generated::CHAIN_HASH;

    type GenesisConfig = GenesisConfig<S>;
    type GenesisInput = GenesisPaths;
    type ModuleExecutionConfig = ();
    type Auth = RollupAuthenticator<S, Self>;

    fn endpoints(api_state: ApiState<S>) -> NodeEndpoints {
        // Three layers compose into the rollup's HTTP surface:
        //
        // 1. Per-module REST routers (e.g. `GET /modules/bank/tokens`),
        //    plumbed through `HasRestApi` from the `RuntimeRestApi`
        //    derive on the inner runtime.
        // 2. The dedup endpoint — replay-protection bookkeeping
        //    against our `sov-uniqueness` module. Wallets hit it to
        //    learn the next-unused nonce for an address.
        // 3. The universal-wallet schema endpoint. Returns the
        //    runtime schema (built at build time, stored in
        //    `__generated::SCHEMA_JSON`) plus the chain hash, so
        //    wallets can construct correctly-bound transactions
        //    without out-of-band schema knowledge.
        let axum_router = Self::default().rest_api(api_state.clone());

        let dedup = SovereignDeDupEndpoint::new(api_state.clone());
        let axum_router = axum_router.merge(dedup.axum_router());

        let schema: Schema = serde_json::from_str(__generated::SCHEMA_JSON)
            .expect("build script must emit a parseable SCHEMA_JSON");
        let schema_endpoint = StandardSchemaEndpoint::<S>::new(
            &schema,
            Self::CHAIN_HASH.into(),
            api_state.checkpoint_receiver(),
        )
        .expect("build script CHAIN_HASH must be the canonical 32 bytes");
        let axum_router = axum_router.merge(schema_endpoint.axum_router());

        NodeEndpoints { axum_router, ..Default::default() }
    }

    fn genesis_config(input: &Self::GenesisInput) -> anyhow::Result<Self::GenesisConfig> {
        // Promote the typed `GenesisError` (used by ligate-stf
        // internals) to `anyhow::Error` for the SDK's blueprint API,
        // which is `anyhow`-flavoured at this boundary.
        Ok(create_genesis_config(input)?)
    }

    fn operating_mode(genesis: &Self::GenesisConfig) -> OperatingMode {
        genesis.chain_state.operating_mode
    }

    fn wrap_call(
        auth_data: <Self::Auth as sov_modules_api::capabilities::TransactionAuthenticator<S>>::Decodable,
    ) -> <Self as sov_modules_api::DispatchCall>::Decodable {
        // `RollupAuthenticator` has a single decoded variant — it
        // dispatches directly to `Rt::Decodable`. So `wrap_call` is
        // the identity. (Compare the SDK demo's matching `Evm /
        // Solana / Standard` arms — we have none of those.)
        auth_data
    }
}

impl<S: Spec> HasCapabilities<S> for Runtime<S>
where
    S::Address: FromVmAddress<EthereumAddress>,
{
    /// We omit `sov-paymaster`, so the gas-payer slot is `()`. The
    /// SDK's `StandardProvenRollupCapabilities` defaults `GasPayer`
    /// to `()` precisely for this case.
    type Capabilities<'a> = StandardProvenRollupCapabilities<'a, S>;
    type SequencingData = sov_modules_api::HDTimestamp;

    fn capabilities(&mut self) -> Guard<Self::Capabilities<'_>> {
        Guard::new(StandardProvenRollupCapabilities {
            bank: &mut self.0.bank,
            gas_payer: (),
            sequencer_registry: &mut self.0.sequencer_registry,
            accounts: &mut self.0.accounts,
            uniqueness: &mut self.0.uniqueness,
            chain_state: &mut self.0.chain_state,
            operator_incentives: &mut self.0.operator_incentives,
            prover_incentives: &mut self.0.prover_incentives,
            attester_incentives: &mut self.0.attester_incentives,
        })
    }
}

impl<S: Spec> HasKernel<S> for Runtime<S>
where
    S::Address: FromVmAddress<EthereumAddress>,
{
    type Kernel<'a> = SoftConfirmationsKernel<'a, S>;

    fn inner(&mut self) -> Guard<Self::Kernel<'_>> {
        Guard::new(SoftConfirmationsKernel {
            chain_state: &mut self.0.chain_state,
            blob_storage: &mut self.0.blob_storage,
        })
    }

    fn kernel_with_slot_mapping(&self) -> Arc<dyn KernelWithSlotMapping<S>> {
        Arc::new(self.0.chain_state.clone())
    }
}
